# Generated by Django 5.2 on 2025-04-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='file',
        ),
        migrations.AddField(
            model_name='fileresource',
            name='path',
            field=models.CharField(default='C:\\Users\\Lenovo\\Desktop\\模拟共享', max_length=1024),
        ),
    ]
