# Generated by Django 5.2 on 2025-04-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_fileresource_file_fileresource_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
