# Generated by Django 5.2 on 2025-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fileresource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='category',
            field=models.CharField(choices=[('drawing', '图纸'), ('report', '报告'), ('client', '客户资料'), ('other', '其他')], default='other', max_length=50),
        ),
    ]
