# Generated by Django 5.2 on 2025-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_actionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='path',
        ),
        migrations.AddField(
            model_name='fileresource',
            name='file',
            field=models.FileField(default='uploads/placeholde.txt', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
