# Generated by Django 5.1.5 on 2025-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_fileresource_path_fileresource_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='file',
        ),
        migrations.AddField(
            model_name='fileresource',
            name='path',
            field=models.CharField(default='C:\\共享文件\\未分类\\placeholder.txt', max_length=1024),
        ),
    ]
