# Generated by Django 5.1.5 on 2025-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_fileresource_file_fileresource_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='path',
        ),
        migrations.AddField(
            model_name='fileresource',
            name='file',
            field=models.FileField(default='uploads/placeholder.txt', upload_to='uploads/'),
        ),
    ]
