# Generated by Django 5.1.5 on 2025-05-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_fileresource_path_fileresource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
