# Generated by Django 5.1.5 on 2025-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_fileresource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
