# Generated by Django 5.1.5 on 2025-06-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fileresource_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
